CC	 	= armv5te-cross-linux-gnueabi-gcc
CFLAGS  ?= -Wall -Wno-multichar -Wno-unused-but-set-variable -fPIC -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s  -lpthread -ldl -lm -lrt -lstdc++ -L. 

# for LD debug -s

OBJ					= bin/armv5te
EXECUTABLE 			= bin/squeeze2raop-armv5te
EXECUTABLE_STATIC 	= bin/squeeze2raop-armv5te-static

include Makefile

