CFLAGS  ?= -Wall -Wno-multichar -Wno-unused-but-set-variable -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lgomp -lpthread -ldl -lm -lrt -lstdc++ -L. 

OBJ					= bin/x86
EXECUTABLE 			= bin/squeeze2raop-x86
EXECUTABLE_STATIC 	= bin/squeeze2raop-x86-static

include Makefile

