CC	 	= armv6j-cross-linux-gnueabihf-gcc
CFLAGS  ?= -Wall -Wno-multichar -Wno-unused-but-set-variable -fPIC -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -ldl -lm -lrt -lstdc++ -L. 

# for LD debug -s

OBJ					= bin/armv6hf
EXECUTABLE 			= bin/squeeze2raop-armv6hf
EXECUTABLE_STATIC 	= bin/squeeze2raop-armv6hf-static

include Makefile

