CFLAGS  ?= -Wall -Wno-multichar -Wno-unused-but-set-variable -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -lgomp -lpthread -lssl -lcrypto -ldl -lm -lrt -lstdc++ -L. 

OBJ					= bin/x86-64
EXECUTABLE 			= bin/squeeze2raop-x86-64
EXECUTABLE_STATIC 	= bin/squeeze2raop-x86-64-static

include Makefile

