CC	= i386-cross-solaris2.10-gcc
CFLAGS  = -Wall -fPIC -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS = -s -lpthread -ldl -lm -lrt -lsocket -lnsl -lz -lstdc++ -lresolv -L.
OS		= SunOS

OBJ		= bin/i86pc-solaris
EXECUTABLE 			= bin/squeeze2raop-i86pc-solaris
EXECUTABLE_STATIC 	= bin/squeeze2raop-i86pc-solaris-static

include Makefile

