CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -lgomp -lpthread -lssl -lcrypto -ldl -lm -lrt -lz -L. 

# for LD debug -s

OBJ					= bin/armv5hf
EXECUTABLE 			= bin/squeeze2raop-armv5hf
EXECUTABLE_STATIC 	= bin/squeeze2raop-armv5hf-static

include Makefile

