CC	 	= aarch64-cross-linux-gnueabi-gcc
CFLAGS  ?= -Wall -Wno-multichar -Wno-unused-but-set-variable -fPIC -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -ldl -lm -lrt -lstdc++ -L. 

# for LD debug -s

OBJ					= bin/aarch64
EXECUTABLE 			= bin/squeeze2raop-aarch64
EXECUTABLE_STATIC 	= bin/squeeze2raop-aarch64-static

include Makefile

