CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -lgomp -lpthread -lssl -lcrypto -ldl -lm -lrt -lz -lstdc++ -L. 

OBJ					= bin/x86
EXECUTABLE 			= bin/squeeze2raop-x86
EXECUTABLE_STATIC 	= bin/squeeze2raop-x86-static

include Makefile

