CC		 = o64-gcc
CFLAGS  ?= -Wall -fPIC -O2 $(OPTS) $(INCLUDE) $(DEFINES) -arch x86_64
LDFLAGS ?= -lpthread -ldl -lm -lstdc++ -L. -arch x86_64 -mmacosx-version-min=10.10
OS 		 = Darwin

OBJ			= bin/osx
EXECUTABLE		= bin/squeeze2raop-osx-multi
EXECUTABLE_STATIC	= bin/squeeze2raop-osx-multi-static

include Makefile

